grid_map_topic: "/height_mapping/data_collection/map"
grid_map_visualizations:
  - name: "/height_mapping/data_collection/pointcloud"
    type: point_cloud
    params:
      layer: elevation
  - name: "/height_mapping/data_collection/region"
    type: map_region
    params:
      # white
      color: 0xFFFFFF
      line_width: 0.01
