height_mapping:

  # Topics
  pointCloudTopic: "/velodyne_tilted/velodyne_points"
  heightMapTopic: "elevation_grid"
  heightMapCloudTopic: "elevation_cloud"
  featureMapTopic: "elevation_feature"
  publishDebugTopics: true

  # Frame Ids
  baselinkFrame: "base_link"
  mapFrame: "map"

  # Pointcloud Filter
  minHeightThreshold: -0.2
  maxHeightThreshold: 1.5
  minRangeThreshold: 0.3
  maxRangeThreshold: 10.0

  # Height Map
  gridResolution: 0.1
  mapLengthX: 15.0
  mapLengthY: 15.0
  heightEstimatorType: "SimpleMean" # "SimpleMean", "KalmanFilter", "MovingAverage"

  # Process
  poseUpdateRate: 10
  mapVisualizationRate: 10

global_mapping:

  # Topics
  globalMapTopic: "/height_mapping/elevation_cloud_global"
  mapRegionTopic: "/height_mapping/map_region_global"

  # Map parameters
  gridResolution: 0.1
  mapLengthXGlobal: 600
  mapLengthYGlobal: 600
  heightEstimatorType: "SimpleMean" # "SimpleMean", "MovingAverage", "KalmanFilter"

  # Node settings
  globalMapVisualizationRate: 10.0

  # Map saver parameters
  mapSaveDir: "$(find height_mapping)/map_image"
