height_mapping:

  # Topics
  pointCloudTopic: "/velodyne_tilted/velodyne_points"
  heightMapTopic: "gridmap"
  featureMapTopic: "descriptor"

  # Frame Ids
  baselinkFrame: "base_link"
  mapFrame: "map"

  # Point Cloud Filtering
  minHeightThreshold: -0.2
  maxHeightThreshold: 1.5

  # Height Map
  gridResolution: 0.1
  mapLengthX: 15.0
  mapLengthY: 15.0

  pose_update_rate: 30
  map_visualization_rate: 10