global_mapping:
  # Topics
  globalMapTopic: "/height_mapping/elevation_cloud_global"
  mapRegionTopic: "/height_mapping/map_region_global"

  # Map parameters
  gridResolution: 0.1
  mapLengthXGlobal: 600
  mapLengthYGlobal: 600
  heightEstimatorType: "StatMean" # "StatMean", "MovingAverage", "KalmanFilter"

  # Node settings
  globalMapVisualizationRate: 10.0

  # Map saver parameters
  mapSaveDir: "$(find height_mapping)/map_image"
