# Map parameters
gridResolution: 0.1
mapLengthXGlobal: 400
mapLengthYGlobal: 400
heightEstimatorType: "StatMean" # "StatMean", "MovingAverage", "KalmanFilter"

# Node settings
globalMapVisualizationRate: 10.0

# Map saver parameters
mapSaveDir: "$(find height_mapping)/map_image"
