grid_map_topic: "/height_mapping/gridmap"
grid_map_visualizations:
  - name: "/height_mapping/pointcloud"
    type: point_cloud
    params:
      layer: elevation
  - name: "/height_mapping/map_region"
    type: map_region
    params:
      color: 0x000000
      line_width: 0.01
